### ISSUE TITLE
Bug: does nothing on MacOS

### ISSUE THREAD

**Issue by Jackymancs4** [thomascsd/vscode-readme-pattern#1]
Hello @thomascsd 
As the title says, the extension does nothing on MacOS 10.14.5 and VSCode 1.36.1.

My idea is that in both

https://github.com/thomascsd/vscode-readme-pattern/blob/9de4a8c461f3f1538de654b9612b743f59323f80/src/lib/ReadmeWriter.ts#L30

and 

https://github.com/thomascsd/vscode-readme-pattern/blob/9de4a8c461f3f1538de654b9612b743f59323f80/src/lib/ReadmeWriter.ts#L45

you used `path\\file` which works on Windows (resulting in something like `path\to\my\file`, but on both Mac and Linux it results in `path\to\my/file`, as confirmed by the Developer Console.

I have not tested the fix, but I think using `path.join()` instead of string concatenation should work.
Thanks

**Comment by thomascsd** [comment]
I'll fix it soon
Thanks
