### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by shkabo** [thomascsd/vscode-readme-pattern#2]
I'm working on new Symfony 4 project, tried to generate minimal readme, but nothing happened. Had to google around to find your repo and see that this is only for nodejs applications. Maybe extend it to read composer.json, or to generate dummy empty template that can be edited.

**Comment by thomascsd** [comment]
I will extend it to support composer.json.
Fix it soon, thanks

**Comment by thomascsd** [comment]
v1.2.0 has published
