### ISSUE TITLE
feature request, linux compatilty

### ISSUE THREAD

**Issue by AmSaleh21** [thomascsd/vscode-readme-pattern#8]
Why is the extension windows platform-specific, can you add Linux support?
![image](https://user-images.githubusercontent.com/95314680/160500870-576bf866-74c6-4ede-869a-7392cc8b2a6d.png)

**Comment by thomascsd** [comment]
Input thomascsd, you can find this package.

![圖片](https://user-images.githubusercontent.com/7641666/168416277-3a310e1c-e2cf-4725-b2b9-b28f7cf8e0cc.png)

**Comment by AmSaleh21** [comment]
Thanks, for adding it.
checked in ubuntu gnome and lxde in VMs and it is there now, wasn't showing in Manjaro-5.15.32-1 with vscode-1.66.0, but when I updated to vscode-1.67.0 all extensions won't show installed or non. but that is a different issue.

**Comment by AmSaleh21** [comment]
I can find it in ubuntu-22.04 gnome-42 and lubuntu-22.04 but not in Manjaro-21.2.6 on gnome-42.1 for vsCode-1.67.0
![image](https://user-images.githubusercontent.com/95314680/168419724-f2a1378d-30a9-4a2b-8874-2cf057ac1d21.png)

**Comment by AmSaleh21** [comment]
I am closing this issue because apparently too many extensions just do not show or work on manjaro/Arch even ones built by Microsoft and with said support like [remote connections](https://github.com/Microsoft/vscode-remote-release).
sorry for the interruptions.
